/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AltERC721MintingFactory__factory } from "./AltERC721MintingFactory__factory";
export { AltERC721NFTContract__factory } from "./AltERC721NFTContract__factory";
