/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEnoch1,
  IEnoch1Interface,
} from "../../../contracts/Tokens/IEnoch1";

const _abi = [
  {
    inputs: [],
    name: "_owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IEnoch1__factory {
  static readonly abi = _abi;
  static createInterface(): IEnoch1Interface {
    return new utils.Interface(_abi) as IEnoch1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEnoch1 {
    return new Contract(address, _abi, signerOrProvider) as IEnoch1;
  }
}
