/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AdminRegistry__factory } from "./AdminRegistry__factory";
export { IAdminRegistry__factory } from "./IAdminRegistry__factory";
