/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AdminRegistry } from "./AdminRegistry";
export type { IAdminRegistry } from "./IAdminRegistry";
