/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AltERC721MintingFactory } from "./AltERC721MintingFactory";
export type { AltERC721NFTContract } from "./AltERC721NFTContract";
